# Generated by Django 5.0.7 on 2024-10-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsientoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cuenta', models.CharField(max_length=255)),
                ('tipo_cuenta', models.CharField(choices=[('AC', 'Activo Circulante'), ('ANC', 'Activo No Circulante'), ('P', 'Pasivo'), ('PT', 'Patrimonio'), ('G', 'Gastos'), ('C', 'Costo'), ('I', 'Ingresos')], max_length=10)),
                ('tipo_monto', models.CharField(choices=[('Debe', 'Debe'), ('Haber', 'Haber')], max_length=5)),
                ('monto', models.FloatField()),
                ('glose', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
